# Generated by Django 5.1 on 2024-10-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AddField(
            model_name='laboratory',
            name='country',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
