# Generated by Django 5.1 on 2024-10-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_laboratory_options_laboratory_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='leadership_area',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='country',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
